particles_to_ignore = ["\u2019s", "\u2019", "\u201c", "\u201d", "\u2014"]

function_words = [
    # Conjunctions
    "and",
    "but",
    "or",
    "nor",
    "for",
    "so",
    "yet",
    "although",
    "because",
    "before",
    "if",
    "since",
    "though",
    "unless",
    "until",
    "when",
    "where",
    "while",
    "both",
    "either",
    "neither",
    "not only",
    "but also",
    "whether",
    "or",
    "after",
    "once",
    "wherever",
    "as",
    "as if",
    "as long as",
    "as soon as",
    "as though",
    "whereas",
    "provided",
    "assuming",
    "lest",
    "even if",
    "even though",
    "in case",
    "in order that",
    "such that",
    "rather than",
    "so that",
    "now that",
    "than",
    "supposing",
    "whenever",
    "whereas",
    "otherwise",
    "inasmuch as",
    "whereupon",
    "even when",
    "whereby",
    "whilst",
    # Prepositions
    "about",
    "above",
    "across",
    "after",
    "against",
    "along",
    "among",
    "around",
    "at",
    "before",
    "behind",
    "below",
    "beneath",
    "beside",
    "between",
    "beyond",
    "by",
    "despite",
    "down",
    "during",
    "except",
    "for",
    "from",
    "in",
    "inside",
    "into",
    "like",
    "near",
    "of",
    "off",
    "on",
    "onto",
    "out",
    "outside",
    "over",
    "past",
    "since",
    "through",
    "throughout",
    "till",
    "to",
    "toward",
    "under",
    "underneath",
    "until",
    "up",
    "upon",
    "with",
    "within",
    "without",
    "across",
    "amid",
    "amongst",
    "aside",
    "atop",
    "beyond",
    "concerning",
    "despite",
    "excepting",
    "following",
    "regarding",
    "versus",
    "via",
    "according to",
    "alongside",
    "besides",
    "concerning",
    "contrary to",
    "in addition to",
    "in front of",
    "in spite of",
    "instead of",
    "next to",
    "owing to",
    "subsequent to",
    "unlike",
    "with regard to",
    "with respect to",
    "per",
    "plus",
    "within sight of",
    "as per",
    "notwithstanding",
    "apropos of",
    # Articles (Determiners)
    "a",
    "an",
    "the",
    # Pronouns
    "I",
    "me",
    "you",
    "he",
    "him",
    "she",
    "her",
    "it",
    "we",
    "us",
    "they",
    "them",
    "my",
    "mine",
    "your",
    "yours",
    "his",
    "her",
    "hers",
    "its",
    "our",
    "ours",
    "their",
    "theirs",
    "myself",
    "yourself",
    "himself",
    "herself",
    "itself",
    "ourselves",
    "yourselves",
    "themselves",
    "who",
    "whom",
    "whose",
    "which",
    "that",
    "this",
    "that",
    "these",
    "those",
    "who",
    "whom",
    "whose",
    "which",
    "what",
    "whichever",
    "whoever",
    "whomever",
    "whatever",
    "all",
    "another",
    "any",
    "anybody",
    "anyone",
    "anything",
    "both",
    "each",
    "either",
    "everybody",
    "everyone",
    "everything",
    "few",
    "many",
    "most",
    "neither",
    "nobody",
    "none",
    "no one",
    "nothing",
    "one",
    "several",
    "some",
    "somebody",
    "someone",
    "something",
    "anywhere",
    "somewhere",
    "nowhere",
    "everywhere",
    "whosoever",
    "anyhow",
    "somehow",
    "each other",
    "one another",
    "such",
    "anybody else",
    "everyone else",
    "anything else",
    "something else",
    # Auxiliary (Helping) Verbs
    "am",
    "is",
    "are",
    "was",
    "were",
    "be",
    "being",
    "been",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "doing",
    "shall",
    "will",
    "should",
    "would",
    "may",
    "might",
    "must",
    "can",
    "could",
    "ought",
    # Modal Verbs
    "can",
    "could",
    "may",
    "might",
    "must",
    "shall",
    "should",
    "will",
    "would",
    "ought to",
    # Particles
    "no",
    "not",
    "n't",
    "to",
    "up",
    "down",
    "in",
    "out",
    "on",
    "off",
    "over",
    "under",
    "apart",
    "aside",
    "away",
    "back",
    "forward",
    "round",
    "through",
    "along",
    "around",
    "forth",
    "together",
    "ahead",
    # Quantifiers (Determiners)
    "all",
    "another",
    "any",
    "both",
    "each",
    "either",
    "enough",
    "every",
    "few",
    "fewer",
    "little",
    "less",
    "many",
    "more",
    "most",
    "much",
    "neither",
    "no",
    "several",
    "some",
    "such",
    "various",
    "numerous",
    "plenty",
    "sufficient",
    "whole",
    "any",
    "a lot of",
    "loads of",
    "heaps of",
    "dozens of",
    "tons of",
    "ample",
    "quite a few",
    "a couple of",
    "a number of",
    "an abundance of",
    "a handful of",
    "oodles of",
    "no fewer than",
    # Interjections
    "ah",
    "oh",
    "um",
    "er",
    "hmm",
    "eh",
    "wow",
    "oops",
    "hey",
    "alas",
    "bravo",
    "ouch",
    "ugh",
    "phew",
    "yikes",
    "hurray",
    "oopsie",
    "eww",
    "uh-oh",
    "yay",
    "yippee",
    "whoa",
    "darn",
    "jeez",
    "whoops",
    "huh",
    "psst",
    "aha",
    "ooh",
    "shh",
    "tsk",
    "yow",
    "ha",
    "gosh",
    "golly",
    "bam",
    "kapow",
    "rats",
    "sigh",
    # Other Function Words
    "there",
    "here",
    "then",
    "thus",
    "so",
    "also",
    "just",
    "only",
    "even",
    "ever",
    "now",
    "still",
    "yet",
    "already",
    "evermore",
    "hence",
    "thence",
    "wherefore",
    "meanwhile",
    "afterward",
    "beforehand",
    "once",
    "twice",
    "thrice",
    "furthermore",
    "moreover",
    "besides",
    "likewise",
    "nonetheless",
    "anyway",
    "accordingly",
    "consequently",
    "therefore",
    "similarly",
    "indeed",
    "henceforth",
    "heretofore",
    "herein",
    "therein",
    "wherein",
    "whereupon",
    "nevertheless",
    "nonetheless",
    "otherwise",
]


function_words = [f.lower() for f in function_words]
